//returns a string of 6 random alphanumeric characters
const generateRandomString = () => { //helper function
  return Math.random().toString(36).substring(2, 8);
};

//lookup for existing emails and returns the user if its registered
const getUserByEmail = (email, database) => { // helper function
  for (const key in database) {
    if (database[key].email === email) {
      return database[key];
    }
  }
  return undefined;
};

//generates an object for a given user with all the urls generated by him
const urlsForUser = (userID) => { // helper function
  const urls = {};
  for (const shortURL in urlDatabase) {
    if (userID === urlDatabase[shortURL].userID) {
      urls[shortURL] = urlDatabase[shortURL];
    }
  }
  return urls;
};



module.exports = { getUserByEmail, urlsForUser, generateRandomString };